### ISSUE TITLE
Need the ability to add a --bwlimit to rclone

### ISSUE THREAD

**Issue by revilo951** [bardisty/ytdlrc#1]
Loving this tool, but I need to be able to add a bandwidth limit, so it doesn't trash my google drive upload. I like to preserve some upload capacity each day, so I can still use it if I need to.

**Comment by bardisty** [comment]
I've added an `rclone_flags` option, you can set any additional rclone flags there.

``` bash
# Rclone flags
#     * Add any additional rclone flags here, e.g.: "--syslog --bwlimit 5M"
#         * "--config" is already set, see `rclone_config` variable above
#         * If debug=true, "-vv --stats 1s" is appended to rclone command
#         * If debug=false, "-q" is appended to rclone command
rclone_flags="--acd-upload-wait-per-gb 5m"
```

**To update:**

- Navigate to where you downloaded the repository
- If you haven't already:
    - `git add ytdlrc`
    - `git commit -m "Modify options to my taste"`
- `git pull` and merge
