### ISSUE TITLE
Underline title

### ISSUE THREAD

**Issue by uGeek** [bardisty/ytdlrc#10]
It is a great script !!! Congratulations

Would it be possible to remove the underline in the titles of the videos?

Thank you

**Comment by bardisty** [comment]
Thanks @uGeek! Check out issue #4. A few small edits are needed to do that.

**Comment by uGeek** [comment]
Thank you!!!

It is simply spectacular. It works perfectly with your help.

thanks

**Comment by bardisty** [comment]
No problem! Glad to hear everything's working well.
