### ISSUE TITLE
Restricted filenames

### ISSUE THREAD

**Issue by Dawok** [bardisty/ytdlrc#4]
Hi, I love your script and use it to archive some japanese and korean channels. Is there a way to remove `--restrict-filenames` without messing up the script?

**Comment by bardisty** [comment]
Hey thanks, glad you find it useful! I've only tested it without the `--restrict-filenames` flag on one video and it seemed to handle it fine. YMMV, though.

A few small edits needed to make this work.

* Delete line 194 *(affects folder names for the channels on rclone remote)*:
    https://github.com/bardisty/ytdlrc/blob/af7ef723ec4e1bad77b79a3d4d3ef8bf1b234b58/ytdlrc#L194

* Delete line 220 *(affects filenames of downloaded videos and metadata)*:
    https://github.com/bardisty/ytdlrc/blob/af7ef723ec4e1bad77b79a3d4d3ef8bf1b234b58/ytdlrc#L220

* Change `'{}'` to `{}` on line 211:
    ```diff
    - '{}' '${rclone_destination%/}/${video_value}' \
    + {} '${rclone_destination%/}/${video_value}' \
    ```
    https://github.com/bardisty/ytdlrc/blob/af7ef723ec4e1bad77b79a3d4d3ef8bf1b234b58/ytdlrc#L211

**Comment by Dawok** [comment]
I see, got it working. Thank you so much

**Comment by bardisty** [comment]
No problem!
