### ISSUE TITLE
Add an option to delay between downloads

### ISSUE THREAD

**Issue by revilo951** [bardisty/ytdlrc#6]
I'm getting this ` HTTP Error 429: Too Many Requests` a bunch. An option to set a delay between grabs would be fantastic.

Thanks!

**Comment by bardisty** [comment]
You can control the delay between downloads using youtube-dl's `--sleep-interval` option:

 ```shell
--sleep-interval SECONDS
```
> Number of seconds to sleep before each download when used alone or a lower bound of a range for randomized sleep before each download (minimum possible number of seconds to sleep) when used along with `--max-sleep-interval`.

```shell
--max-sleep-interval SECONDS
```

> Upper bound of a range for randomized sleep before each download (maximum possible number of seconds to sleep). Must only be used along with `--min-sleep-interval`.

To add this to `ytdlrc`, find the `download_all_the_things()` function where all of youtube-dl's flags are set:
https://github.com/bardisty/ytdlrc/blob/af7ef723ec4e1bad77b79a3d4d3ef8bf1b234b58/ytdlrc#L204

Then just add it in, e.g.:

```shell
download_all_the_things() {
  # shellcheck disable=SC2086
  youtube-dl \
    --force-ipv4 \
    --continue \
    --download-archive "$ytdl_archive_list" \
    --exec "rclone $rclone_command \
      '{}' '${rclone_destination%/}/${video_value}' \
      --config '$rclone_config' \
      $rclone_flags \
      $rclone_debug_flags" \
    --format "$ytdl_format" \
    --ignore-config \
    --ignore-errors \
    --no-overwrites \
    --output "${ytdl_download_dir%/}/${video_value}/${ytdl_output_template}" \
    --restrict-filenames \
    --sleep-interval 10 \
    --write-description \
    --write-info-json \
    --write-thumbnail \
    "$ytdl_debug_flags" \
    $ytdl_subtitle_flags \
    $ytdl_xattrs_flag \
    "$1"
}
```

Hopefully that helps. If not you might need to get a new IPv4 IP or use a proxy:

https://github.com/ytdl-org/youtube-dl#http-error-429-too-many-requests-or-402-payment-required

There's been github issues about this problem for years, though it appears there's been an influx of new ones related to it beginning around July 9th:

- https://github.com/ytdl-org/youtube-dl/issues?page=1&q=HTTP+Error+429&utf8=%E2%9C%93
- https://github.com/ytdl-org/youtube-dl/issues/21729

You might want to explore those issues for other potential solutions.

**Comment by revilo951** [comment]
Well, that'll work. Hopefully, I don't need to get a new IPv4 address. On that note, why you do you specify the `--force-ipv4` flag?

**Comment by bardisty** [comment]
> On that note, why you do you specify the `--force-ipv4` flag?

Mostly because performance was significantly better over IPv4 during initial testing _(2 years ago)_, and because a lot of people experience issues with YouTube blocking IPv6 addresses of various hosts (OVH, DigitalOcean, etc.) due to abuse.

If you have IPv6 setup, feel free to remove the flag and see how things are. If it's fine, that might be all you need to avoid the 429 error.
